[package]
name = "sol-usdc-arb-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
tokio = {version="1.47.1",features=["full"]}
tonic = "0.14.2"
tungstenite = "0.27.0"
yellowstone-grpc-client = "9.0.0"
yellowstone-grpc-proto = "9.0.0"
